### ISSUE TITLE
es7.6报了这个错误，请问怎么解决

### ISSUE THREAD

**Issue by liufei96** [Kestrong/datax-elasticsearch#8]
com.alibaba.datax.common.exception.DataXException: Code:[Framework-13], Description:[DataX插件运行时出错, 具体原因请参看DataX运行结束时的错误诊断信息 .].  - java.lang.UnsupportedOperationException: JsonObject
        at com.google.gson.JsonElement.getAsLong(JsonElement.java:230)
        at io.searchbox.core.SearchResult.getTotal(SearchResult.java:218)
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.transportRecords(EsReader.java:285)
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.startRead(EsReader.java:159)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:748)
 - java.lang.UnsupportedOperationException: JsonObject
        at com.google.gson.JsonElement.getAsLong(JsonElement.java:230)
        at io.searchbox.core.SearchResult.getTotal(SearchResult.java:218)
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.transportRecords(EsReader.java:285)
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.startRead(EsReader.java:159)
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57)
        at java.lang.Thread.run(Thread.java:748)

        at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:40) ~[datax-common-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.scheduler.processinner.ProcessInnerScheduler.dealFailedStat(ProcessInnerScheduler.java:39) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.scheduler.AbstractScheduler.schedule(AbstractScheduler.java:99) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.schedule(JobContainer.java:535) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:119) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.start(Engine.java:92) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.entry(Engine.java:171) [datax-core-0.0.1-SNAPSHOT.jar:na]
        at com.alibaba.datax.core.Engine.main(Engine.java:204) [datax-core-0.0.1-SNAPSHOT.jar:na]
java.lang.UnsupportedOperationException: JsonObject
        at com.google.gson.JsonElement.getAsLong(JsonElement.java:230) ~[na:na]
        at io.searchbox.core.SearchResult.getTotal(SearchResult.java:218) ~[na:na]
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.transportRecords(EsReader.java:285) ~[na:na]
        at com.alibaba.datax.plugin.reader.elasticsearchreader.EsReader$Task.startRead(EsReader.java:159) ~[na:na]
        at com.alibaba.datax.core.taskgroup.runner.ReaderRunner.run(ReaderRunner.java:57) ~[datax-core-0.0.1-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]

**Comment by Kestrong** [comment]
@liufei96 已修复，原因是es7以上的版本返回json结构改变，导致io.searchbox组件中获取getTotal报错，该组件已经不维护了，目前先注释掉用到该方法的log日志，后续考虑更换es的组件。
